### ISSUE TITLE
Bundle modifying the Genfile.lock file (Setting up an Environment)

### ISSUE THREAD

**Issue by JhonSidney** [linkvan/linkvan-api#25]
## Description of the issue below:

  - After executing the `bundle` command the file" Gemfile.lock "changes.

- ####  Command `$  git diff`:
![image](https://user-images.githubusercontent.com/18706961/110259550-00765680-7f87-11eb-804c-1183a1e91dc7.png)

- #### Problem image:

![image](https://user-images.githubusercontent.com/18706961/110259376-1c2d2d00-7f86-11eb-88b6-4644f8f88e26.png)

**Comment by fabionl** [comment]
@JhonSidney 

I updated several gem versions and consequently Gemfile.lock was also updated. Hopefully, you won't have this issue anymore. If you do, please update the ticket with the new Gemfile.lock diff.
