### ISSUE TITLE
List of Facilities

### ISSUE THREAD

**Issue by fabionl** [linkvan/linkvan-api#6]
## User Stories

AS a Facility Admin
I WANT TO see a list of my facilities
SO I can View, Edit, Add, Delete

AS an Admin
I WANT TO see a list of all facilities
SO I can View, Edit, Delete, Approve/Disapprove Facilities.

## Scenarios

- [x] Scenario: Information shown in list of Facilities

GIVEN I'm on a list of facilities
THEN I want to see an overview of each facility.

List of expected informations:
- Facility Name
- Last Updated
- Services
- Welcomes
- Status (Pending Review / Live)
- Available Actions'

---

- [x] Scenario: Adding new Facilities

GIVEN I'm seeing list of facilities
WHEN I click on Add New Facility
THEN I want to see the new Facility form
AND I should be the owner of the created facility.

List of expected fields:
- Welcomes
- Services
- Address
- Location in a Google Maps (Optional for v1.0)
- Phone number
- Website
- Hours (With all seven days of week)
- Notes

---

- [x] Scenario: Editting Facilities

GIVEN I have the right to edit a facility
WHEN I click on its Edit action
THEN a Edit Facility form similar to the new facility form

---

- [x] Scenario: Delete Facilities

GIVEN I have the right to delete a facility
WHEN I click on its Delete action
THEN I want the see a confirmation dialog
AND if I confirm, I want the facility to be removed of the list

**Comment by JhonSidney** [comment]
- #### I'm working in Scenario: Information shown in list of Facilities
