### ISSUE TITLE
Clicking on Edit from Hamburger goes to different path to clicking on Facility Name

### ISSUE THREAD

**Issue by Shadey88** [linkvan/linkvan-api#70]
When you Click on the Name of the  Facility in the Main Facility Menu it goes to a different page to when you click on Edit in the Hamburger Menu.

**Comment by fabionl** [comment]
# Notes / TODO:

- Add navigation (breadcrumbs or back button)
- Switching Facility switch button.
- Rearrange:
- Top box for Status toggle
- Welcomes/Services to last
- Left Side:
- Notes/Description
- Facility Details (Edit form content in one box)
- Right Side:
- Schedule (first right)
- Welcomes/Services:
- Headers: Yes/No; Note
- Schedule: Add in-screen without new form; "+" button below trash button; Open All Day/Closed All Day

- Facilities index: Order by name; hamburger menu; Add phone number;

- Facility Live/Draft
- Change Transgender to LGBTQ2S+
